example.property: "I AM A PROD PROPERTY OVERRIDE"
spring.jpa.database: "MYSQL"
spring.datasource.platform:  "mysql"
spring.jpa.show-sql: "true"
spring.database.driverClassName: "com.mysql.jdbc.Driver"
spring.datasource.url: "jdbc:mysql://localhost:3306/eagle_eye_local?useSSL=false&serverTimezone=UTC"
spring.datasource.username: "root"
spring.datasource.password: "falcon123"
spring.datasource.testWhileIdle: "true"
spring.datasource.validationQuery: "SELECT 1"
spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.MySQL5InnoDBDialect"
redis.server: "redis"
redis.port: "6379"
signing.key: "345345fsdfsf5345"
spring.jpa.hibernate.ddl-auto: "update"